/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include <string.h>
#include "lx_api.h"

#ifndef LX_STANDALONE_ENABLE
/* Supply the application hook required by the shared ThreadX library.  */
VOID tx_application_define(VOID *first_unused_memory)
{
    (void) first_unused_memory;
}
#endif

/* Check page ECC correction across both 256-byte portions of a page.  */
int main(void)
{

LX_NAND_FLASH  flash = {0};
USHORT         storage[256];
UCHAR         *page = (UCHAR *) storage;
UCHAR          expected[512];
UCHAR          ecc[6];
UINT           i;
UINT           bit;
int            failed = 0;

    flash.lx_nand_flash_bytes_per_page = 512;
    for (i = 0; i < 512; i++)
    {
        expected[i] = (UCHAR) (i & 0xFFU);
    }
    memcpy(page, expected, sizeof(expected));
    if (lx_nand_flash_page_ecc_compute(&flash, page, ecc) != LX_SUCCESS)
    {
        failed = 1;
    }
    if (lx_nand_flash_page_ecc_check(&flash, page, ecc) != LX_SUCCESS)
    {
        failed = 1;
    }

    /* Every single data bit must be corrected without changing other bytes.  */
    for (i = 0; i < 512; i++)
    {
        for (bit = 0; bit < 8; bit++)
        {
            memcpy(page, expected, sizeof(expected));
            page[i] ^= (UCHAR) (1U << bit);
            if (lx_nand_flash_page_ecc_check(&flash, page, ecc) != LX_NAND_ERROR_CORRECTED)
            {
                failed = 1;
            }
            if (memcmp(page, expected, sizeof(expected)) != 0)
            {
                failed = 1;
            }
        }
    }

    /* Corrections in both portions must retain the corrected status.  */
    page[0] ^= 1U;
    page[256] ^= 1U;
    if (lx_nand_flash_page_ecc_check(&flash, page, ecc) != LX_NAND_ERROR_CORRECTED)
    {
        failed = 1;
    }
    if (memcmp(page, expected, sizeof(expected)) != 0)
    {
        failed = 1;
    }

    /* An uncorrectable second portion must override a first-portion correction.  */
    page[0] ^= 1U;
    page[256] ^= 3U;
    if (lx_nand_flash_page_ecc_check(&flash, page, ecc) != LX_NAND_ERROR_NOT_CORRECTED)
    {
        failed = 1;
    }
    memcpy(page, expected, sizeof(expected));
    page[0] ^= 3U;
    if (lx_nand_flash_page_ecc_check(&flash, page, ecc) != LX_NAND_ERROR_NOT_CORRECTED)
    {
        failed = 1;
    }

    return(failed);
}
