/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "lx_api.h"

/* Verify unaligned metadata access and NAND workspace alignment.  */
int main(void)
{
LX_NAND_FLASH nand_flash;
ULONG         workspace[1024];
UCHAR         metadata[16];
UINT          status;
UINT          index;
UINT          page_offset;

    LX_MEMSET(metadata, 0xA5, sizeof(metadata));
    LX_UTILITY_SHORT_SET(&metadata[1], 0x1234u);
    LX_UTILITY_LONG_SET(&metadata[5], 0x89ABCDEFu);

    if ((LX_UTILITY_SHORT_GET(&metadata[1]) != 0x1234u) ||
        (LX_UTILITY_LONG_GET(&metadata[5]) != 0x89ABCDEFu))
    {
        return 1;
    }

    for (index = 0; index < sizeof(metadata); index++)
    {
        if ((index != 1u) && (index != 2u) &&
            (index != 5u) && (index != 6u) &&
            (index != 7u) && (index != 8u) &&
            (metadata[index] != 0xA5u))
        {
            return 2;
        }
    }

    LX_MEMSET(&nand_flash, 0, sizeof(nand_flash));
    nand_flash.lx_nand_flash_total_blocks = 127u;
    nand_flash.lx_nand_flash_bytes_per_page = 512u;
    nand_flash.lx_nand_flash_spare_total_length = 16u;

    status = _lx_nand_flash_memory_initialize(&nand_flash, workspace, 2848u);
    if (status != LX_SUCCESS)
    {
        return 3;
    }

    page_offset = (UINT)(nand_flash.lx_nand_flash_page_buffer - (UCHAR *)workspace);
    if ((page_offset != 1792u) ||
        ((page_offset % sizeof(ULONG)) != 0u) ||
        (nand_flash.lx_nand_flash_page_buffer_size != 1056u))
    {
        return 4;
    }

    status = _lx_nand_flash_memory_initialize(&nand_flash, workspace, 1791u);
    if (status != LX_NO_MEMORY)
    {
        return 5;
    }

    status = _lx_nand_flash_memory_initialize(&nand_flash, workspace, 2847u);
    if (status != LX_NO_MEMORY)
    {
        return 6;
    }

    nand_flash.lx_nand_flash_total_blocks = 128u;
    status = _lx_nand_flash_memory_initialize(&nand_flash, workspace, 2848u);
    if (status != LX_SUCCESS)
    {
        return 7;
    }

    page_offset = (UINT)(nand_flash.lx_nand_flash_page_buffer - (UCHAR *)workspace);
    if ((page_offset != 1792u) || ((page_offset % sizeof(ULONG)) != 0u))
    {
        return 8;
    }

    return 0;
}
