/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026-present Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

// Some portions generated by Copilot (Sonnet 4.6).

/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** LevelX Component                                                      */
/**                                                                       */
/**   NAND Flash                                                          */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/

#define LX_SOURCE_CODE


/* Disable ThreadX error checking.  */

#ifndef LX_DISABLE_ERROR_CHECKING
#define LX_DISABLE_ERROR_CHECKING
#endif


/* Include necessary system files.  */

#include "lx_api.h"


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _lx_nand_flash_defragment                           PORTABLE C      */
/*                                                           6.2.1       */
/*  AUTHOR                                                                */
/*                                                                        */
/*    William E. Lamie, Microsoft Corporation                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function defragments the NAND flash.                           */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    nand_flash                            NAND flash instance           */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    return status                                                       */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    _lx_nand_flash_block_reclaim          Reclaim a NAND flash block    */
/*    tx_mutex_get                          Get thread protection         */
/*    tx_mutex_put                          Release thread protection     */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    Application Code                                                    */
/*    Internal LevelX                                                     */
/*                                                                        */
/**************************************************************************/
UINT  _lx_nand_flash_defragment(LX_NAND_FLASH *nand_flash)
{

#ifdef LX_NAND_FLASH_ENABLE_LAZY_SECTOR_RELEASE

UINT    status;
ULONG   lg;

    /* Compact every logical group that has a deferred compaction pending.  */
    for (lg = 0; lg < nand_flash -> lx_nand_flash_total_blocks; lg++)
    {

        if (nand_flash -> lx_nand_flash_block_compaction_table[lg] != (USHORT)LX_NAND_BLOCK_UNMAPPED)
        {

            status = _lx_nand_flash_logical_group_compact(nand_flash, lg);

            /* On error, continue to compact remaining groups.  */
            if (status)
            {
                _lx_nand_flash_system_error(nand_flash, status, lg, 0);
            }
        }
    }

    return(LX_SUCCESS);

#else

    LX_PARAMETER_NOT_USED(nand_flash);

    /* Return not supported.  */
    return(LX_NOT_SUPPORTED);

#endif /* LX_NAND_FLASH_ENABLE_LAZY_SECTOR_RELEASE */
}


