/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026-present Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

// Some portions generated by Codex (GPT-5).


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** LevelX Component                                                      */
/**                                                                       */
/**   NOR Flash                                                           */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/

#define LX_SOURCE_CODE


/* Disable ThreadX error checking.  */

#ifndef LX_DISABLE_ERROR_CHECKING
#define LX_DISABLE_ERROR_CHECKING
#endif


/* Include necessary system files.  */

#include "lx_api.h"


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _lx_nor_flash_driver_write                          PORTABLE C      */
/*                                                           6.2.1       */
/*  AUTHOR                                                                */
/*                                                                        */
/*    William E. Lamie, Microsoft Corporation                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function performs a write of the NOR flash memory.             */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    nor_flash                             NOR flash instance            */
/*    flash_address                         Address of NOR flash to write */
/*    source                                Source for the write          */
/*    words                                 Number of words to write      */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    return status                                                       */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    (lx_nor_flash_driver_write)           Actual driver write           */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    Application Code                                                    */
/*                                                                        */
/**************************************************************************/
UINT  _lx_nor_flash_driver_write(LX_NOR_FLASH *nor_flash, ULONG *flash_address, ULONG *source, ULONG words)
{

#ifndef LX_NOR_DISABLE_EXTENDED_CACHE

UINT    status;
UINT    i;
ULONG   *cache_entry_start;
ULONG   cache_entry_start_value;
ULONG   cache_entry_end_value;
ULONG   cache_offset;
ULONG   flash_address_value;


    /* Is the request a whole sector or a partial sector.  */
    if ((words == 1) && (nor_flash -> lx_nor_flash_extended_cache_entries))
    {

        /* One word request, which implies that it is a NOR flash metadata write.  */

        /* MISRA C:2012 Rule 11.4 deviation: NOR driver addresses may be logical
           address tokens, including zero, so compare address values without
           dereferencing them.  */
        flash_address_value =  (ULONG)flash_address;

        /* Loop through the cache entries to see if there is a sector in cache.  */
        for (i = 0; i < nor_flash -> lx_nor_flash_extended_cache_entries; i++)
        {

            /* Search through the cache to see if there is a cache entry.  */

            /* Determine the cache entry addresses.  */
            cache_entry_start =  nor_flash -> lx_nor_flash_extended_cache[i].lx_nor_flash_extended_cache_entry_sector_address;

            /* Determine if the flash address is in the cache entry.  */
            if (nor_flash -> lx_nor_flash_extended_cache[i].lx_nor_flash_extended_cache_entry_valid)
            {
                cache_entry_start_value =  (ULONG)cache_entry_start;
                cache_entry_end_value =    cache_entry_start_value + (LX_NOR_SECTOR_SIZE * sizeof(ULONG));

                if ((flash_address_value >= cache_entry_start_value) && (flash_address_value < cache_entry_end_value))
                {

                    /* Yes, we found the entry.  */

                    /* Calculate the offset into the cache entry.  */
                    cache_offset =  (flash_address_value - cache_entry_start_value) / sizeof(ULONG);

                    /* Copy the word into the cache.  */
                    *(nor_flash -> lx_nor_flash_extended_cache[i].lx_nor_flash_extended_cache_entry_sector_memory + cache_offset) =  *source;

                    /* Get out of the loop.  */
                    break;
                }
            }
        }
    }

    /* In any case, call the actual driver write function.  */
#ifdef LX_NOR_ENABLE_CONTROL_BLOCK_FOR_DRIVER_INTERFACE
    status =  (nor_flash -> lx_nor_flash_driver_write)(nor_flash, flash_address, source, words);
#else
    status =  (nor_flash -> lx_nor_flash_driver_write)(flash_address, source, words);
#endif

    /* Return completion status.  */
    return(status);

#else
UINT    status;


    /* Call the actual driver write function.  */
#ifdef LX_NOR_ENABLE_CONTROL_BLOCK_FOR_DRIVER_INTERFACE
    status =  (nor_flash -> lx_nor_flash_driver_write)(nor_flash, flash_address, source, words);
#else
    status =  (nor_flash -> lx_nor_flash_driver_write)(flash_address, source, words);
#endif

    /* Return completion status.  */
    return(status);
#endif
}
